server: 8080

spring:

  web:
    servlet:
      context-path: /api

  application:
    name: soundscape

  datasource:
    username:
    password:
    url:
    driver-class-name:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret_key: 6ed1eb0150e8f8fb285ec976ce500807406933985fbea5086c690eb221e53f5a
      expiration: 8640000