server: 8080

spring:

  web:
    servlet:
      context-path: /api

  application:
    name: soundscape

  servlet:
    multipart:
      max-file-size: 50MB

  datasource:
    username:
    password:
    url:
    driver-class-name:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: sparklecow
    password: sparklecow
    properties:
      smtp:
        trust: "*"
      auth: true
      starttls:
        enable: true
      connectiontimeout: 5000
      timeout: 3000
      writetimeput: 5000

application:
  security:
    jwt:
      secret_key: 6ed1eb0150e8f8fb285ec976ce500807406933985fbea5086c690eb221e53f5a
      expiration: 8640000